version: '3.3'

services:
  client:
    container_name: web4_client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - .:/var/www/ionic_docker
